import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

import { auth, signOut } from "#/auth";

import { getSupabaseClient } from "@/lib/supabase-client";

async function quitSession() {
  "use server";
  await signOut({ redirectTo: "/" });
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const supabase = await getSupabaseClient(session);
  const { data } = await supabase.from("users").select("*");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="absolute top-0 pt-4 pb-4 min-h-20 w-full flex flex-row gap-16 items-center justify-center lg:gap-24">
          <div />
          {data && data.length > 0 && (
            <form action={quitSession}>
              <button
                className="text-xl text-slate-700 font-bold"
                type="submit"
              >
                Logout
              </button>
            </form>
          )}
          <Link
            className="text-3xl text-center text-slate-700 font-bold"
            href="/"
          >
            Home
          </Link>
          {data && data.length === 0 && (
            <Link className="text-xl text-slate-700 font-bold" href="/login">
              Login
            </Link>
          )}
          {data && data.length > 0 && (
            <Link className="text-xl text-slate-700 font-bold" href="/notes">
              Notes
            </Link>
          )}
          {data && data.length > 0 && (
            <Link className="text-xl text-slate-700 font-bold" href="/profile">
              <Image src={data[0].image || ""} width={40} height={40} alt="profile" />
            </Link>
          )}
        </nav>
        {children}
      </body>
    </html>
  );
}
