import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="absolute top-0 p-4 min-h-20 w-full gap-4 flex justify-between lg:justify-center lg:gap-20">
          <Link className="text-xl text-slate-700 font-bold" href="/signup">
            Sign Up
          </Link>
          <Link className="text-3xl text-slate-700 font-bold" href="/">
            Home
          </Link>
          <Link className="text-xl text-slate-700 font-bold" href="/login">
            Login
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
